### ISSUE TITLE
Still Unknown Functions！

### ISSUE THREAD

**Issue by liliang1213** [brendangregg/FlameGraph#97]
Hi,I use '--perf-basic-prof' option while profiling nodejs,and I also get a file named '/tmp/perf-PID.map' under /tmp directory, but when I generate flame graph using 'perf script | ./stackcollapse-perf.pl | ./flamegraph.pl > MAIN.svg', it remains many 'unknown' label in my graph, how could that be?
Thank you!

perf script command returns like this:
![image](https://cloud.githubusercontent.com/assets/5275852/16798361/41e0fba6-491e-11e6-8b05-8541f293230c.png)

**Comment by brendangregg** [comment]
I'm going to close this ticket because it's not a problem with Flame Graphs, which visualize the profiler output. If the profiler is emitting "[unknown]", then fix the profiler. It's system software, so ask your OS vendor.

I'd check if perf was complaining about file permissions, and fix that. Another issue has been buffering in v8, which was fixed recently -- look it up in v8 bug tracking, I don't have the URL on hand. I don't know when that fix will arrive in node, if it isn't there already. There are other issues that can cause "[unknown]" too, especially in JIT runtimes.

**Comment by lasergnu** [comment]
Had this issue just now on CentOS Linux release 8.2.2004

The following helped get rid of many [unknown]:

perf record -F 99 -a -g --call-graph dwarf,16578
